# Generated by Django 4.2.4 on 2023-08-17 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptedUserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('encrypted_email', models.BinaryField()),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
