# Generated by Django 4.2.4 on 2023-08-21 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeviceInformation',
        ),
    ]
